# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - left_finger_joint
    sim_control_mode: 1  # 0: position, 1: velocity
left_finger_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
        - left_finger_joint
    gains:
        left_finger_joint: { p: 1000.0, d: 1.0, i: 0.1, i_clamp: 100 }
    constraints:
        goal_time: 2.0
        stopped_velocity_tolerance: 0.05
        left_finger_joint: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate: 25
    action_monitor_rate: 10