controller_list:
  - name: r1_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r1shoulder_pan_joint
      - r1shoulder_lift_joint
      - r1elbow_joint
      - r1wrist_1_joint
      - r1wrist_2_joint
      - r1wrist_3_joint
  - name: r2_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r2shoulder_pan_joint
      - r2shoulder_lift_joint
      - r2elbow_joint
      - r2wrist_1_joint
      - r2wrist_2_joint
      - r2wrist_3_joint
  - name: r3_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r3shoulder_pan_joint
      - r3shoulder_lift_joint
      - r3elbow_joint
      - r3wrist_1_joint
      - r3wrist_2_joint
      - r3wrist_3_joint
  - name: r1_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r1gripper_finger1_joint
  - name: r2_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r2gripper_finger1_joint
  - name: r3_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - r3gripper_finger1_joint